spring:
  application:
    name: big-event
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /api
