spring:
  application:
    name: big-event
  datasource:
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /api

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*Mapper.xml

token:
  header: Authorization
  secret: abcdefghijklmlaassfff
  expire_minutes: 30
